"""Added sellerId

Revision ID: 0e6fe26aabc7
Revises: fdda4f629687
Create Date: 2025-01-25 13:37:30.068806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6fe26aabc7'
down_revision = 'fdda4f629687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('sellerId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sellers', 'sellers', ['sellerId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'sellerId')
    # ### end Alembic commands ###
