"""Removed name and added other variables

Revision ID: 8adf3b0b1abe
Revises: 741300a31496
Create Date: 2024-10-30 11:17:18.676831

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8adf3b0b1abe"
down_revision = "741300a31496"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendors", sa.Column("full_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "vendors", sa.Column("first_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("middle_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("last_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column("vendors", sa.Column("profile_picture", sa.String(), nullable=True))
    op.add_column("vendors", sa.Column("jwt_token_key", sa.String(), nullable=True))
    op.add_column(
        "vendors", sa.Column("password_last_updated", sa.DateTime(), nullable=True)
    )
    op.add_column("vendors", sa.Column("preferences", sa.JSON(), nullable=True))
    op.add_column(
        "vendors", sa.Column("notification_preferences", sa.String(), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("verification_expiration", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("language_code", sa.String(length=35), nullable=True)
    )
    op.add_column("vendors", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.add_column("vendors", sa.Column("verification_code", sa.String(), nullable=True))
    op.add_column("vendors", sa.Column("date_of_birth", sa.String(), nullable=True))
    op.add_column("vendors", sa.Column("gender", sa.String(length=10), nullable=True))
    op.add_column(
        "vendors", sa.Column("is_email_verified", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("is_phone_verified", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("two_factor_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column("vendors", sa.Column("two_factor_secret", sa.String(), nullable=True))
    op.add_column(
        "vendors", sa.Column("notifications_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "vendors", sa.Column("ai_recommendation_opt_in", sa.Boolean(), nullable=True)
    )

    # Alter column with explicit casting to boolean using the USING clause
    op.alter_column(
        "vendors",
        "is_active",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="is_active::boolean",
    )

    op.drop_index("ix_vendors_name", table_name="vendors")
    op.drop_column("vendors", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendors", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_vendors_name", "vendors", ["name"], unique=False)
    op.alter_column(
        "vendors",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("vendors", "ai_recommendation_opt_in")
    op.drop_column("vendors", "notifications_enabled")
    op.drop_column("vendors", "two_factor_secret")
    op.drop_column("vendors", "two_factor_enabled")
    op.drop_column("vendors", "is_phone_verified")
    op.drop_column("vendors", "is_email_verified")
    op.drop_column("vendors", "gender")
    op.drop_column("vendors", "date_of_birth")
    op.drop_column("vendors", "verification_code")
    op.drop_column("vendors", "is_admin")
    op.drop_column("vendors", "language_code")
    op.drop_column("vendors", "verification_expiration")
    op.drop_column("vendors", "notification_preferences")
    op.drop_column("vendors", "preferences")
    op.drop_column("vendors", "password_last_updated")
    op.drop_column("vendors", "jwt_token_key")
    op.drop_column("vendors", "profile_picture")
    op.drop_column("vendors", "phone_number")
    op.drop_column("vendors", "last_name")
    op.drop_column("vendors", "middle_name")
    op.drop_column("vendors", "first_name")
    op.drop_column("vendors", "full_name")
    # ### end Alembic commands ###
